Dash Interface Refactor
mwang87/MetabolomicsSpectrumResolver pull request #152
Opened 2021-04-13 17:39 UTC by mwang87

2021-04-29 23:17 UTC, bittremieux requested changes
Ok, I did a first pass. I haven't used Dash before, so I'm still somewhat wrapping my head around it. It doesn't have the cleanest code with defining the interface like that, but I guess raw HTML also just sucks.

I have a few comments already. I might have some more comments when I've been able to think a bit more about the architecture as well.

Sometimes the dashboard seems to automagically refresh, even if I didn't change any input values. I'm not sure what's going on, but it's a bit annoying.

2021-04-30 16:20 UTC, mwang87 commented on dashinterface.py
> +def determine_task(pathname, search):
Yeah, this is run right at the first loading of the page.

2021-04-30 17:00 UTC, mwang87 commented on dashinterface.py
> +    mirror_url = f"/svg/mirror/?{urlencode(plotting_args, quote_via=quote)}"
yeah i think you already cleaned up, seems to work!

2021-04-30 17:01 UTC, mwang87 commented on dashinterface.py
> +    usi1_url = f"/svg/?{urlencode(plotting_args, quote_via=quote)}"
looks good and works as cleaned up.

2021-04-30 17:01 UTC, mwang87 commented on dashinterface.py
> +    r = requests.get(local_url)  # TODO: What happens with `r`?
This is to keep the caching warm, because the issue in returning the image tag instead of an actual image, it takes a while to change.

2021-04-30 17:15 UTC, mwang87 commented on dashinterface.py
> +    spectrum = views._prepare_spectrum(spectrum, **cleaned_plotting_args)
OK there might not be a great way to actually accommodate this because the set of inputs that change the image vs the table are different.

2021-05-06 01:14 UTC, bittremieux commented on dashinterface.py
> +def determine_task(pathname, search):
Ok, if I understand the code correctly this takes the parameters from the URL and populates the settings? Do we need `pathname`? It's not used in the method.

2021-05-06 02:11 UTC, mwang87 commented
So it’s still needed I think because it triggers the function to be called
on page load. It’s like a dummy input dependency.

On Wed, May 5, 2021 at 6:14 PM Wout Bittremieux ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In dashinterface.py
> <https://github.com/mwang87/MetabolomicsSpectrumResolver/pull/152#discussion_r627014102>
> :
>
> > +        Output("usi2", "value"),
> +        Output("width", "value"),
> +        Output("height", "value"),
> +        Output("mz_min", "value"),
> +        Output("mz_max", "value"),
> +        Output("max_intensity", "value"),
> +        Output("annotate_precision", "value"),
> +        Output("annotation_rotation", "value"),
> +        Output("cosine", "value"),
> +        Output("fragment_mz_tolerance", "value"),
> +        Output("grid", "value"),
> +    ],
> +    [Input("url", "pathname")],
> +    [State("url", "search")],
> +)
> +def determine_task(pathname, search):
>
> Ok, if I understand the code correctly this takes the parameters from the
> URL and populates the settings? Do we need pathname? It's not used in the
> method.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mwang87/MetabolomicsSpectrumResolver/pull/152#discussion_r627014102>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAXSEFJ6V2UDDBWYH53MNLTMHUPRANCNFSM423ZBQNQ>
> .
>

2021-05-08 01:59 UTC, bittremieux commented
Don't be mad Ming, but I changed way too many things. 😳 I think I (mostly) managed to improve the code a bit though. One thing is currently broken: labeling peaks and syncing that with the peak table.
The Celery task processing also suddenly stopped working during the day. I don't think I modified that code, but maybe I inadvertently did so.

2021-05-08 02:00 UTC, bittremieux commented on dashinterface.py
> +_example_usi = "mzspec:MSV000082796:KP_108_Positive:scan:1974"
This spectrum doesn't look super great (the small peak at 1500 m/z). Is this a special spectrum? Can we find a more interesting default USI?

2021-08-17 21:49 UTC, closed without merging