[WIP] Add feature to allow for peak passing directly into mirror plots
mwang87/MetabolomicsSpectrumResolver pull request #177
Opened 2021-10-21 22:32 UTC by benpullman

This feature will allow for the input of spectrum peaks instead of USIs for mirror plots for mirror plot end points (but not the UI yet).

I added a new method which allows for the input of a USI or a spectrum, reads the USI first, but if the USI is empty, reads the spectrum peaks input as a JSON.

Please let me know if there's a different approach that should be taken for this.

2021-11-09 00:53 UTC, benpullman commented
Just a note that some tests fail, but I think its not a result of the updates that I made here.

2021-11-10 02:49 UTC, benpullman commented
@mwang87 @bittremieux I switched the input type to PROXI - I was pretty lenient with what terms could be use for precursor m/z and modified peptide as seen here - not sure exactly how broad a net we want to cast for what terms are allowed for what.

```    for attribute in spectrum["attributes"]:
        # isolation window target m/z
        if attribute["accession"] == "MS:1000827":
            precursor_mz = float(attribute["value"])
        # selected ion m/z
        elif attribute["accession"] == "MS:1000744":
            precursor_mz = float(attribute["value"])
        # charge state
        elif attribute["accession"] == "MS:1000041":
            charge = int(attribute["value"])
        # spectrum name (peptidoform?)
        elif attribute["accession"] == "MS:1003061":
            peptide = attribute["value"].split("/")[0]
        # peptidoform
        elif attribute["accession"] == "MS:1003049":
            peptide = attribute["value"]
        # unmodified peptide sequence
        elif attribute["accession"] == "MS:1000888":
            peptide_clean = attribute["value"]

2021-11-11 01:07 UTC, bittremieux requested changes
Looks pretty good. A few comments for small changes.

Some of the tests are failing because the SSL certificate of the SPLASH web API has expired. I'll send an email to Fiehn to let him know.

2021-11-11 02:07 UTC, benpullman commented on metabolomics_spectrum_resolver/tasks.py
>  cached_parse_usi = memory.cache(parsing.parse_usi)
I wasn't sure if we wanted to do this.  There are still cases of just `parse_usi` that we need to handle.

2021-11-11 02:12 UTC, benpullman commented on metabolomics_spectrum_resolver/tasks.py
> +    Parameters
Fixed.

2021-11-11 02:12 UTC, benpullman commented on metabolomics_spectrum_resolver/views.py
> +@blueprint.route("/png/mirror/", methods=["GET", "POST"])
Done.

2021-11-11 02:12 UTC, benpullman commented on test/peak_test_data.py
> +]
Added.

2021-11-11 02:13 UTC, benpullman commented
@bittremieux Thanks for the comments, they made a ton of sense and I addressed everything except the caching.  I wasn't completely sure how to handle the caching though.

2021-11-11 02:13 UTC, bittremieux commented on metabolomics_spectrum_resolver/tasks.py
>  cached_parse_usi = memory.cache(parsing.parse_usi)
Ok, that's possible. I didn't check in full detail. We can leave it in now, but should revisit it at some point to avoid code duplication.

2021-11-11 02:15 UTC, bittremieux commented
Great, thanks. Yeah, we can leave the caching in right now and revisit it in the near future.

Fiehn also emailed back that they're aware of the SSL issues, but that it's challenging to fix. So we can ignore those failed unit tests for now.

2021-11-12 01:07 UTC, merged